### PR TITLE
use duckdb v0.10.0

### PR DESCRIPTION
**Pull request by romainfrancois**

### CODE REVIEW

**Comment by krlmlr** [comment]
Please merge when green. I assume you updated the tag to v0.10.0?

**Comment by romainfrancois** [comment]
yes, `git checkout v0.10.0` on the `duckdb/` directory

**Comment by romainfrancois** [comment]
🤔 there's actually more to do ... trying again

**Comment by romainfrancois** [comment]
oh that's interesting, there was probably some changes in `duckdb` 0.10.0 about how dates and times are downcasted, and so shelving some tests for now. They were only falsely working as we started to identify in #56  anyway.

**Comment by romainfrancois** [comment]
@krlmlr I'll let you double check the files in `.github/workflows` because I'm not sure about those. But it seems to ✅ now

**Comment by krlmlr** [comment]
Thanks!

**Pull request merged**
